### PR TITLE
Cluster Sharding

### PR DESCRIPTION
**Pull request by manuelbernhardt**
This exercise introduces Cluster Sharding (not sure about the exercise number, I just picked an index that wouldn't interfere).

Still to do:
- create the exercise instructions, come up with meaningful things to observe and questions
- maybe think of a way to emphasize rebalancing (like, flash the LEDs faster when an entity has been moved, or make it brighter, or something like that)

### CODE REVIEW

**Comment by eloots** [comment]
@manuelbernhardt Ran this exercise on my cluster - worked perfectly!
I've been thinking about other ways to visualise cluster sharding. One alternative is to just visualise the number of entities on the node using some color encoding scheme that doesn't use too many colours.
With 10 LEDs available where LED # 10 is used to show some form of heartbeat, the nine remaining LEDs can be used to encode a number in base 4, but with a twist:
For example; yellow (`Y`) encodes `1`, orange (`O`) encodes `4`, red (`R`) encodes `16`. In this way, counts between 0 (no LEDs on), 1 (1 Yellow LED), and 63 can be encoded. So:

```
0: No LEDs on
1: Y
2: Y Y
3: Y Y Y
4: O
5: O Y
6: O Y Y
7: O Y Y Y
8: O O
9: O O Y
.
.
.
15: O O O Y Y Y
16: R
.
.
.
62: R R R O O O Y Y
63: R R R O O O Y Y Y
```

I think that being able to encode up-to 63 entities per node if pretty high for demo purposes.

Alternatively, one could use a simple binary encoding with one color, but that would require some effort (and calculation skills) on the of the observer. With 9 LEDs, this would allow to encode an entity count of up to 511 per node.

WDYT?

**Comment by manuelbernhardt** [comment]
@eloots I played a bit more with this, and realized that this wasn't showing shards. So I built this now: https://www.youtube.com/watch?v=-cOllO8yQw8

So now each shard has two entities and the entities of a same shard have the same color. Also, the entities shift to take the place of the ones that moved to another node.

Note that LED actuation needs to be serialized because otherwise two entity actors will concurrently try to send signals to the strip, and that doesn't work well at all.

**Comment by manuelbernhardt** [comment]
@eloots about using base 4 to show more entities: I wonder if that's not a bit too abstract to understand? I'm thinking the "one entity per LED" is probably the most staightforward representation, and you can easily see individual entities (actually, shards) move around

**Comment by manuelbernhardt** [comment]
@eloots one thing I intend to add is for entities that are freshly allocated to appear in a brighter color when they blink the first time (or times). Is there any way to do this? I saw that brightness can be controlled for the whole strip, but I wonder if this can be achieved for individual LEDs?

**Comment by eloots** [comment]
> @eloots about using base 4 to show more entities: I wonder if that's not a bit too abstract to understand? I'm thinking the "one entity per LED" is probably the most staightforward representation, and you can easily see individual entities (actually, shards) move around

You're correct: moving to using one LED/shard is much better + it obviates the need showing large numbers. Obviously, the limitation is that, if only one node is in the cluster, you cannot visualise _all_ shards as there are only nine LEDs. I don't really see that as a problem.

**Comment by eloots** [comment]
> @eloots one thing I intend to add is for entities that are freshly allocated to appear in a brighter color when they blink the first time (or times). Is there any way to do this? I saw that brightness can be controlled for the whole strip, but I wonder if this can be achieved for individual LEDs?

@manuelbernhardt 

Brightness is set at a global level (unfortunately). Also, max brightness (`255`) is way too bright to be useful. That's why in the current exercises, global brightness is set at `10` (so 1/25.5 of max value). The setting (`cluster-status-indicator.led-brightness`) is in `reference.conf` in project `common`. It might be worth the effort to add a function that allows one to set a color with a given [relative] brightness. In this way, we could bump the global brightness level to a much higher value and sent the relative brightness starting from there. The method to do this with just apply a scaling of the RGB values passed in. Makes sense?
Some experimentation would be desirable to verify the practicality and usefulness of this approach...

**Comment by manuelbernhardt** [comment]
@eloots I've used this demonstration during a training now (as you know), I think it's good enough for the time being. WDYT?

**Comment by manuelbernhardt** [comment]
Hmm, that being said, I just remembered I need still to add exercise instructions here

**Comment by eloots** [comment]
@manuelbernhardt LGTM
Maybe you can use LED's 9 and 10 for showing two additional things:
- LED 9: (self) node status (Up, Joining, ...)
- LED 10: Overflow: when this LED is on, it means that there more shards running on the node than can be displayed using the 7 available LED's
I wonder if you can use some other color scheme for showing the shards (using generated colours instead of the hard-coded ones)

**Comment by eloots** [comment]
It seems I started numbering my Akka Typed versions of the exercises starting at exercise 60... which conflicts with the exercise number you chose for this exercise... Shall I renumber mine or you your exercise?

**Comment by eloots** [comment]
@manuelbernhardt 
Let's close this one ?

**Pull request closed without merging**
